ALTER USER HR ACCOUNT UNLOCK;
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'HR';

SELECT * FROM EMPLOYEES;

CREATE USER javaid IDENTIFIED BY 123456;
GRANT CONNECT, RESOURCE TO javaid;