ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER javaid IDENTIFIED BY 123456;
GRANT CONNECT, RESOURCE TO javaid;

ALTER USER JAVAID IDENTIFIED BY 123456;
SELECT USERNAME FROM ALL_USERS ORDER BY USERNAME;
SELECT username, account_status FROM dba_users WHERE username = 'JAVAID';
CREATE TABLE MEMBER (
    ID       VARCHAR2(20),
    PWD      VARCHAR2(20) NOT NULL,
    NAME     VARCHAR2(50) NOT NULL,
    PHONE    VARCHAR2(20),
    AUTH    NUMBER(1)DEFAULT 0
);
DROP TABLE "MEMBER";

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_ID PRIMARY KEY (ID);

SELECT * FROM MEMBER;

CREATE TABLE MENU (
    ID       NUMBER,
    NAME     VARCHAR2(100) NOT NULL,
    PRICE    NUMBER NOT NULL
);

SELECT ID, NAME, PRICE FROM MENU;
SELECT * FROM MENU;
DESC MENU;

ALTER TABLE MENU
ADD CONSTRAINT MENU_ID PRIMARY KEY (ID);

CREATE TABLE CART (
  ID         NUMBER,
  MEMBER_ID  VARCHAR2(20),
  MENU_ID    NUMBER,
  QUANTITY   NUMBER,
  STATUS     VARCHAR2(10),      -- 결제 후 다시 결제하는 일을 방지하기 위해 추가함. 'IN_CART' or 'PAID'
  REG_DATE   DATE DEFAULT SYSDATE
);

DESC CART;

CREATE TABLE PAYMENT (
  PAY_ID       NUMBER,
  MEMBER_ID    VARCHAR2(20),
  PAY_DATE     DATE DEFAULT SYSDATE,
  TOTAL_AMOUNT NUMBER,
  PAY_METHOD   VARCHAR2(20), -- 결제 수단
  STATUS       VARCHAR2(10) -- 결제 완료 / 결제 취소 'DONE', 'CANCEL'
);

CREATE TABLE PAY_LOG (
  LOG_ID      NUMBER PRIMARY KEY,
  PAY_ID      NUMBER,
  MENU_ID     NUMBER,
  MENU_NAME   VARCHAR2(100),
  QUANTITY    NUMBER,
  PRICE       NUMBER,
  LOG_TYPE    VARCHAR2(20), -- 'PAY', 'CANCEL'
  LOG_TIME    DATE DEFAULT SYSDATE
);

SELECT * FROM PAYMENT;

DROP TABLE PAYMENT;

ALTER TABLE PAYMENT
ADD CONSTRAINT PAY_ID_PK PRIMARY KEY (PAY_ID);

ALTER TABLE PAYMENT
ADD CONSTRAINT MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID);

DROP TABLE PAY_LOG;

ALTER TABLE PAY_LOG
ADD CONSTRAINT FK_PAYLOG_PAYMENT
FOREIGN KEY (PAY_ID)
REFERENCES PAYMENT(PAY_ID);

ALTER TABLE PAY_LOG
ADD CONSTRAINT FK_PAYLOG_MENU
FOREIGN KEY (MENU_ID)
REFERENCES MENU(ID);

SELECT * FROM CART;

DROP TABLE CART;

DELETE FROM CART WHERE MEMBER_ID = 'admin';

ALTER TABLE CART
ADD CONSTRAINT CART_PK PRIMARY KEY (ID);

ALTER TABLE CART
ADD CONSTRAINT CART_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID)
ON DELETE CASCADE;

ALTER TABLE CART
ADD CONSTRAINT CART_MENU_FK FOREIGN KEY (MENU_ID) REFERENCES MENU(ID)
ON DELETE CASCADE;
//멤버 샘플
INSERT INTO MEMBER VALUES('drkim','123456','김박사','010-1592-3814',0);
INSERT INTO MEMBER VALUES('admin','admin123','관리자','010-9999-9999',1);
SELECT * FROM MEMBER;
DELETE FROM MEMBER WHERE "ID" = 'drkim';
//메뉴 샘플
INSERT INTO MENU VALUES(1,'불고기버거',5000);
INSERT INTO MENU VALUES(2,'데리버거',4500);
INSERT INTO MENU VALUES(3,'감자튀김',2000);
INSERT INTO MENU VALUES(4,'콜라',1500);
INSERT INTO MENU VALUES(5,'소프트콘',1000);
//카트 샘플
INSERT INTO CART VALUES(1,'drkim',2,2,10000);
SELECT * FROM CART;

// 시퀀스
CREATE SEQUENCE MENU_SEQ
START WITH 6
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE PAYMENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE PAY_LOG_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

SELECT * FROM MEMBER;
SELECT * FROM MENU;

SELECT * FROM CART WHERE MEMBER_ID = 'admin';
SELECT * FROM CART WHERE MEMBER_ID = ?

// 현재 메뉴 ID의 최댓값(5)과 메뉴시퀀스의 최댓값(2)이 동일하지가 않아서
// 무결성 제약 조건에 위배가 되서 에러가 뜨는 상황이다
SELECT MAX(ID) FROM MENU;
SELECT MENU_SEQ.CURRVAL FROM DUAL;
// 때문에 MENU_ID와 MENU_SEQ가 동기화를 필수적으로 해야한다..
CREATE OR REPLACE TRIGGER MENU_ID_TRG
BEFORE INSERT ON MENU
FOR EACH ROW
BEGIN
  :NEW.ID := MENU_SEQ.NEXTVAL;
END;
/

SELECT * FROM MENU WHERE ID = 10;

COMMIT;