ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER javaid IDENTIFIED BY 123456;
GRANT CONNECT, RESOURCE TO javaid;

SELECT USERNAME FROM ALL_USERS ORDER BY USERNAME;

CREATE TABLE MEMBER (
    ID       VARCHAR2(20),
    PWD      VARCHAR2(20) NOT NULL,
    NAME     VARCHAR2(50) NOT NULL,
    PHONE    VARCHAR2(20),
    AUTH    NUMBER(1)DEFAULT 0
);
DROP TABLE "MEMBER";
ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_ID PRIMARY KEY (ID);


CREATE TABLE MENU (
    ID       NUMBER,
    NAME     VARCHAR2(100) NOT NULL,
    PRICE    NUMBER NOT NULL
);

ALTER TABLE MENU
ADD CONSTRAINT MENU_ID PRIMARY KEY (ID);

CREATE TABLE CART (
    NO         NUMBER,
    MEMBER_ID  VARCHAR2(20),
    MENU_ID    NUMBER,
    QUANTITY   NUMBER DEFAULT 1,
    TOTAL      NUMBER
);

CREATE TABLE PAYMENT(
    PAY_ID      NUMBER,
    MEMBER_ID   VARCHAR(20),
    PAY_DATE    DATE NOT NULL,
    PRICE       NUMBER NOT NULL
);

ALTER TABLE PAYMENT
ADD CONSTRAINT PAY_ID_PK PRIMARY KEY (PAY_ID);

ALTER TABLE PAYMENT
ADD CONSTRAINT MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID);

ALTER TABLE PAYMENT
MODIFY PAY_DATE NOT NULL;

ALTER TABLE PAYMENT
MODIFY PRICE NOT NULL;

DROP TABLE CART;

ALTER TABLE CART
ADD CONSTRAINT CART_PK PRIMARY KEY (NO);

ALTER TABLE CART
ADD CONSTRAINT CART_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID)
ON DELETE CASCADE;

ALTER TABLE CART
ADD CONSTRAINT CART_MENU_FK FOREIGN KEY (MENU_ID) REFERENCES MENU(ID)
ON DELETE CASCADE;
//멤버 샘플
INSERT INTO MEMBER VALUES('drkim','123456','김박사','010-1592-3814',0);
INSERT INTO MEMBER VALUES('admin','admin123','관리자','010-9999-9999',1);
SELECT * FROM MEMBER;
DELETE FROM MEMBER WHERE "ID" = 'drkim';
//메뉴 샘플
INSERT INTO MENU VALUES(1,'불고기버거',5000);
INSERT INTO MENU VALUES(2,'데리버거',4500);
INSERT INTO MENU VALUES(3,'감자튀김',2000);
INSERT INTO MENU VALUES(4,'콜라',1500);
INSERT INTO MENU VALUES(5,'소프트콘',1000);
//카트 샘플
INSERT INTO CART VALUES(1,'drkim',2,2,10000);
SELECT * FROM CART;

// 시퀀스
CREATE SEQUENCE MENU_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

SELECT * FROM MENU;

// 현재 메뉴 ID의 최댓값(5)과 메뉴시퀀스의 최댓값(2)이 동일하지가 않아서
// 무결성 제약 조건에 위배가 되서 에러가 뜨는 상황이다
SELECT MAX(ID) FROM MENU;
SELECT MENU_SEQ.CURRVAL FROM DUAL;
// 때문에 MENU_ID와 MENU_SEQ가 동기화를 필수적으로 해야한다..
CREATE OR REPLACE TRIGGER MENU_ID_TRG
BEFORE INSERT ON MENU
FOR EACH ROW
BEGIN
  :NEW.ID := MENU_SEQ.NEXTVAL;
END;
/

SELECT * FROM MENU WHERE ID = 10;

COMMIT;