SELECT * FROM TAB;
-- 테이블 구조를 볼 수 있다
DESCRIBE TAB;
-- EMPLOYEES; 테이블 전체내용
DESC EMPLOYEES;
SELECT * FROM EMPLOYEES;
-- ID, NAME, EMAIL 내용선택 출력(별칭사용)
SELECT EMPLOYEE_ID AS 아이디 , FIRST_NAME AS 이름, LAST_NAME AS 성,EMAIL AS 이메일 FROM EMPLOYEES;
SELECT EMPLOYEE_ID 아이디 , FIRST_NAME 이름, LAST_NAME 성,EMAIL 이메일 FROM EMPLOYEES;
SELECT EMPLOYEE_ID AS "회사 아이디" , FIRST_NAME "이름", LAST_NAME "성",EMAIL "이메일" FROM EMPLOYEES;
-- EMPLOYEE 테이블 ID가 107번 사원만 보여주세요.(IF(EMPLOYEE_ID == 107) => WHERE)
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 107;
-- EMPLOYEE 테이블 ID가 107번 ~ 110번 사원들만 보여주세요.(IF(EMPLOYEE_ID >= 107 AND EMPLOYEE_ID <= 110) => WHERE)
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID >= 107 AND EMPLOYEE_ID <= 110;
-- EMPLOYEE 테이블 이름이 D로 시작되는 사원들을 보여주세요.(IF(NAME.INDEXOF("D") == 0) => WHERE NAME LIKE D%)
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%d';
-- '_D%' '_D_F%''%D%' '%D'