SELECT FIRST_NAME, SALARY FROM EMPLOYEES;

DROP TABLE BOOKS;
CREATE TABLE BOOKS ( 
    BOOK_ID NUMBER(4), 
    TITLE VARCHAR2(50),
    PUBLISHER VARCHAR2(30), 
    YEAR VARCHAR2(10), 
    PRICE NUMBER(6), 
    PRIMARY KEY(BOOK_ID) 
);
DROP SEQUENCE books_seq;
CREATE SEQUENCE books_seq 
START WITH 1 
INCREMENT BY 1 ;

INSERT INTO books VALUES (books_seq.nextval, 'Operating System Concepts', 'Wiley', '2003',30700); 
INSERT INTO books VALUES (books_seq.nextval, 'Head First PHP and MYSQL', 'OReilly', '2009', 58000); 
INSERT INTO books VALUES (books_seq.nextval, 'C Programming Language', 'Prentice-Hall', '1989', 35000); 
INSERT INTO books VALUES (books_seq.nextval, 'Head First SQL', 'OReilly', '2007', 43000); 

SELECT * FROM books;
DELETE FROM BOOKS WHERE BOOK_ID = 5;
UPDATE books SET title = 'OS', PUBLISHER = 'usd', YEAR = '2025', PRICE = 20000 WHERE book_id = 1;
ROLLBACK;
COMMIT;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES;

DROP TABLE ALBUM;
CREATE TABLE ALBUM ( 
    ALBUM_ID NUMBER(4), 
    TITLE VARCHAR2(50),
    RATE NUMBER (2,1) CHECK(RATE BETWEEN 0.0 AND 5.0),
    ARTIST VARCHAR2(30), 
    RELEASE_DATE DATE
);
ALTER TABLE ALBUM
ADD CONSTRAINT ALBUM_ID_PK PRIMARY KEY (ALBUM_ID);

DROP SEQUENCE ALBUM_SEQ;
CREATE SEQUENCE ALBUM_SEQ
START WITH 1 
INCREMENT BY 1 ;

INSERT INTO ALBUM VALUES (ALBUM_SEQ.nextval, '킁',4.5 ,'C JAMM', TO_DATE('2019-05-16','YYYY,MM,DD')); 
INSERT INTO ALBUM VALUES (ALBUM_SEQ.nextval, 'Lifes Like',4.0 ,'JAZZY FACT', TO_DATE('2010-10-26','YYYY,MM,DD')); 
INSERT INTO ALBUM VALUES (ALBUM_SEQ.nextval, 'FREE THE BEAST',4.5 ,'B-FREE', TO_DATE('2020-11-15','YYYY,MM,DD')); 
INSERT INTO ALBUM VALUES (ALBUM_SEQ.nextval, 'glow forever',2.5 ,'The Quiett', TO_DATE('2018-09-07','YYYY,MM,DD')); 

SELECT * FROM ALBUM;
DELETE FROM ALBUM WHERE BOOK_ID = 5;
UPDATE ALBUM SET title = '', RATE = '', ARTIST = , RELEASE_DATE = TO_DATE('--','YYYY,MM,DD')) WHERE ALBUM_ID = ;
ROLLBACK;
COMMIT;